##### squeeze 从数组的形状中删除一维条目
        --numpy.squeeze 函数从给定数组的形状中删除一维的条目，函数格式如下：
                numpy.squeeze(arr, axis)
                arr:输入的数组
                axis:整数或整数元组，选择删除一个维度

In [48]:
import numpy as np

In [49]:
x = np.arange(9).reshape(1,3,3)
x

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [50]:
print("数组x: ")
print(x,"\n")
y = np.squeeze(x)


print("数组z: ")
print(z,"\n")

print(x.shape, y.shape)

数组x: 
[[[0 1 2]
  [3 4 5]
  [6 7 8]]] 

数组z: 
[[0 1 2]
 [3 4 5]
 [6 7 8]] 

(1, 3, 3) (3, 3)


cv2.circle()方法用来在任何图上画圆圈
    --cv2.cricle(image, center_coordinates, radius, color, thickness)
            image:要绘制圆的图
            center_coordinates:圆的中心坐标2个值的是tuple（x,y）
            thickness;圆的边界线的粗细像素

##### numpy.zero() 创建指定大小的数组，数组元素以0来填充
        --numpy.zeros(shape, dtype=float, order = "c")
                 shape:数组形状
                 dtype:数据类型
                 order："C"用于行数组， ”F“用于列数组

In [71]:
import numpy as np
x = np.zeros((2,4, 3), dtype = int)# 2个这样的3行，4列的矩阵
x  #默认float类型

#自定义数据类型
y = np.zeros((2,2,3), dtype = [("x","i4"),("y","i4")])
y

array([[[(0, 0), (0, 0), (0, 0)],
        [(0, 0), (0, 0), (0, 0)]],

       [[(0, 0), (0, 0), (0, 0)],
        [(0, 0), (0, 0), (0, 0)]]], dtype=[('x', '<i4'), ('y', '<i4')])

##### numpy.ones() 创建指定大小的数组，数组元素以0来填充
        --numpy.zeros(shape, dtype=float, order = "c")
                 shape:数组形状
                 dtype:数据类型
                 order："C"用于行数组， ”F“用于列数组

In [86]:
import numpy as np
x = np.ones((5),dtype=int)
x

#自定义类型
y = np.ones((2,3,2),dtype=int)
y



array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [87]:

z = np.ones([2,3,2], dtype=int)
z

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [110]:
x12 =np.array([
      [2,2,3,4,5],
      [3,2,3,4,5],
      [4,5,3,4,5],
      [5,2,3,4,5]])

x12[:,:2]# ":,"取第一列， ",:2"取到第二列以前，不包括第二列

array([[2, 2],
       [3, 2],
       [4, 5],
       [5, 2]])